### ISSUE TITLE
How to get SysStartTime and SysEndTime values.

### ISSUE THREAD

**Issue by ferplain** [glautrou/EfCoreTemporalTable#20]
Hello.
I am testing this nuget package to get data and filter of Temporal Versioned Tables

I have defined a test model with two added columns `SysStartTime`and `SysEndTime`:
```csharp
    public class Department2
    {
        public int Id { get; set; }
        public string DeptName { get; set; }
        public int ManagerId { get; set; }
        public int ParentDeptID { get; set; }
        public DateTime SysStartTime { get; }
        public DateTime SysEndTime { get; }
    }
```

And I have defined my modelConfiguration for that columns in this way:

```csharp
            entity
                .Property(p => p.SysStartTime)
                .ValueGeneratedOnAddOrUpdate();

            entity
                .Property(p => p.SysEndTime)
                .ValueGeneratedOnAddOrUpdate();
```

When I get the entyre table data with EF Core (without any filtering clause), then all data is fine and I can see the `SysStartTime` and `SysEndTime` without any problem.

But If I try to use this nuget package and filter in this way (for example):

```csharp
return _context
                .Department2
                .AsTemporalContained(from.UtcDateTime, to.UtcDateTime)
                .ToList();
```

Then I have an error with this message:
```
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'WebApiSqlVersionedTables.Data.TestContext'.
      System.InvalidOperationException: The required column 'SysEndTime' was not present in the results of a 'FromSql' operation.
         at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.BuildIndexMap(IReadOnlyList`1 columnNames, DbDataReader dataReader)
         at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.MoveNext()
      System.InvalidOperationException: The required column 'SysEndTime' was not present in the results of a 'FromSql' operation.
         at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.BuildIndexMap(IReadOnlyList`1 columnNames, DbDataReader dataReader)
         at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.MoveNext()

```

Do you have any idea how can I get the values for that columns in the right way?

Thanks in advance and congratulations for your work.

**Comment by glautrou** [comment]
Hi ferplain and thank you,

Please try the following code:
```
entity.Property(e => e.SysStartTime).HasComputedColumnSql("GENERATED ALWAYS AS ROW START"); 
entity.Property(e => e.SysEndTime).HasDefaultValueSql("(CONVERT([datetime2],'9999-12-31 23:59:59.9999999'))");
```

This is what I use in my projects.

FYI by default the dotnet ef scaffold generates the code below, which is wrong because the scaffolder doesn't check for temporal columns (hopefully EF 6.0 should fix that):
`entity.Property(e => e.SysStartTime).HasDefaultValueSql(`"(sysutcdatetime())`");`
If like me you are using DB first then use a Powershell to correctly adapt your DbContext (basically this is juste a string replacement).

**Comment by ferplain** [comment]
Thank you for your answer -and sorry my delay- but no luck with the `property` modifications proposed. 
Same error.

I think the SQL code generated is wrong.
I get right results from this EF Query witch generates this SQL code:

EF Query:
```csharp
return await _context.Department2.ToListAsync();
```
SQL Query generated:
```sql
SELECT [d].[DeptID], [d].[DeptName], [d].[ManagerId], [d].[ParentDeptID], [d].[SysEndTime], [d].[SysStartTime]
FROM [Department2] AS [d]
```

Results:
```json
[
  {
    "id": 10,
    "deptName": "Marketing",
    "managerId": 101,
    "parentDeptID": 1,
    "sysStartTime": "2021-07-06T14:48:24.3349913",
    "sysEndTime": "9999-12-31T23:59:59.9999999"
  },
  {
    "id": 12,
    "deptName": "Sistemas",
    "managerId": 101,
    "parentDeptID": 1,
    "sysStartTime": "2021-07-06T14:48:37.3584988",
    "sysEndTime": "9999-12-31T23:59:59.9999999"
  }
]
```

But **with same model.cs and modelconfiguration.cs** if I try with this EF query then I get a code error:

EF Query:
```csharp
return await _context
                .Department2
                .AsTemporalContained(result.From.UtcDateTime, result.To.UtcDateTime)
                .ToListAsync();
```
SQL Query generated:
```sql
SELECT * FROM [Department2] FOR SYSTEM_TIME CONTAINED IN (@p0, @p1)
',N'@p0 datetime2(7),@p1 datetime2(7)',@p0='2021-07-06 14:21:00',@p1='9999-12-31 23:59:59.9999999'
```
Then, as I said, I get this error:
```csharp
System.InvalidOperationException: The required column 'SysEndTime' was not present in the results of a 'FromSql' operation.
```
It seems as the columns `SysStartTime` and `SysEndTime` are not returned from SQL because they are never requested to database inside the query.

I think the problem is using `*` as columns for the SQL query.

Thanks and regards.

**Comment by glautrou** [comment]
Hi @ferplain and sorry for the delay.

Did you add an `HIDDEN `flag to your system columns? (e.g. : `ALTER TABLE [dbo].[Department2] ALTER COLUMN [SysEndTime] ADD HIDDEN`
Perhaps your column is hidden that's why `*` doesn't work because hidden columns must be explicitly specified in query. But if this is the case I don't understand why EF Core throw an exception instead of silently ignoring extra columns.

If not, can you please post:
- `CREATE TABLE` script
- DbContext
- Model
